# Generated by Django 4.2.30 on 2026-09-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaystoreTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=50)),
                ("status", models.CharField(blank=True, default="", max_length=50)),
                ("amount", models.BigIntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, default="", max_length=10)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
